project:
  type: website

website:
  title: "DCE-blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://uk.linkedin.com/company/data-centric-engineering/
    background: rgb(157, 202, 242)
    logo: images/DCE-mod.png
format:
  html:
    theme: default
    css: styles.css
